## Ildebrando Magnani

* Intro to Numpy:

In [1]:
import numpy as np

In [9]:
# Problem 1:

A = np.array([[3, -1, 4],
              [1, 5,  -9]])
B = np.array([[2, 6, -5,   3],
              [5, -8, 9,   7],
              [9, -3, -2, -3]])

def p1(M1, M2):
    return M1.dot(M2)

p1(A, B)

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

In [10]:
# Problem 2:

A = np.array([[ 3, 1, 4],
              [ 1, 5, 9],
              [-5, 3, 1]])

def p2(M):
    operator = -M@M@M + 9*M@M - 15*M
    return operator

p2(A)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [11]:
# Problem3:

D = np.ones(7)
E = np.zeros(7)
upD = np.triu(D)

A = E + upD

G = np.full_like(D, -1)
H = np.full_like(D, 6)
upH = np.triu(H)

B = G + upH

def p3(M1, M2):
    dot = (M1@M2)@M1
    dot = dot.astype(np.int64)
    return dot

p3(A, B)

array([[ -1,   4,  15,  32,  55,  84, 119],
       [ -6,  -6,   0,  12,  30,  54,  84],
       [ -5, -10,  -9,  -2,  11,  30,  55],
       [ -4,  -8, -12, -10,  -2,  12,  32],
       [ -3,  -6,  -9, -12,  -9,   0,  15],
       [ -2,  -4,  -6,  -8, -10,  -6,   4],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -1]])

In [12]:
# Probelm 4:

def p4(arr):
    arrc = np.copy(arr)
    arrc[arrc<0] = 0
    return arrc

In [13]:
# Problem 5:

A = np.array([[0, 2, 4],
              [1, 3, 5]])
B = np.array([[3, 0, 0],
              [3, 3, 0],
              [3, 3, 3]])
C = np.array([[-2, 0 ,  0],
              [0 , -2,  0],
              [0 ,  0, -2]])

def p5(A, B, C):
    R1 = np.hstack((np.zeros((3,3)), A.T, np.identity(3)))
    R2 = np.hstack((A, np.zeros((2,2)), np.zeros((2,3))))
    R3 = np.hstack((B, np.zeros((3, 2)), C))
    stacked = np.vstack((R1, R2, R3))
    return stacked

p5(A, B, C)

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

In [14]:
# Problem 6:

def p6(A):
    sum = A.astype(np.float64).sum(axis=1)
    sum = sum.T
    return A/sum

In [15]:
# Problem 7:

grid = np.load("/Users/ildebrandomagnani/Desktop/BootCamp2017/Computation/Wk1_PyIntro/grid.npy")

def p7(grid):
    a = np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
    b = np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:,:])
    c = np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1,2:-1] * grid[3:,3:])
    d = np.max(grid[:-3,3:] * grid[1:-2,2:-1] * grid[2:-1,1:-2] *grid[3:,0:-3])
    values = np.array([a, b, c, d])
    max_val = np.max(values)
    return max_val

print(p7(grid), " = max value")

70600674  = max value
