# Ildebrando Magnani

#### QR Decomposition 1 Problems

In [2]:
import numpy as np
from scipy import linalg as la

In [37]:
# Problem 1

def mod_GS(A):
    m, n = A.shape
    Q = A.copy()
    R = np.zeros((n, n))
    for i in range(n):
        R[i,i] = la.norm(Q[:,i])
        Q[:,i] = Q[:,i] / R[i,i]
        for j in range(i+1,n):
            R[i,j] = Q[:,j].T @ Q[:,i]
            Q[:,j] = Q[:,j] - R[i,j]*Q[:,i]
    return Q, R
    

In [78]:
A = np.random.random((4, 4))

In [79]:
Q, R = mod_GS(A)
A_1 = la.inv(A)
print(A_1@A)

[[  1.00000000e+00   0.00000000e+00   8.88178420e-16   0.00000000e+00]
 [  5.55111512e-17   1.00000000e+00   0.00000000e+00  -1.11022302e-16]
 [  1.11022302e-16   4.44089210e-16   1.00000000e+00   1.11022302e-16]
 [ -2.22044605e-16  -4.44089210e-16  -3.33066907e-16   1.00000000e+00]]


In [80]:
print(Q.T@Q, "Q^T Q")
print(R, "R")
print(Q@R, "Q R")
print(A, "A")

[[  1.00000000e+00   4.44089210e-16  -3.46944695e-16   5.55111512e-17]
 [  4.44089210e-16   1.00000000e+00  -2.22044605e-16   4.16333634e-16]
 [ -3.46944695e-16  -2.22044605e-16   1.00000000e+00   0.00000000e+00]
 [  5.55111512e-17   4.16333634e-16   0.00000000e+00   1.00000000e+00]] Q^T Q
[[ 0.486646    1.54743593  1.18568422  0.99443958]
 [ 0.          0.77179048  0.6965319   0.33801005]
 [ 0.          0.          0.55782875  0.29508616]
 [ 0.          0.          0.          0.17449575]] R
[[ 0.31706999  0.76821722  0.93789777  0.76223957]
 [ 0.20050403  0.85231076  0.47083641  0.52807995]
 [ 0.30066177  0.89070428  0.36966945  0.32718034]
 [ 0.0754426   0.93822869  0.98192771  0.50374687]] Q R
[[ 0.31706999  0.76821722  0.93789777  0.76223957]
 [ 0.20050403  0.85231076  0.47083641  0.52807995]
 [ 0.30066177  0.89070428  0.36966945  0.32718034]
 [ 0.0754426   0.93822869  0.98192771  0.50374687]] A


In [99]:
# Problem 2

def det_QR(A):
    m, n = A.shape
    if la.det(A) != 0 and n == m:
        Q, R = mod_GS(A)
        R_diag = np.diagonal(R)
        abs_det_A = np.abs(np.prod(R_diag))
    else:
        print("Input Matrix is not invertible")
    return abs_det_A

In [100]:
det_A = det_QR(A)
print(det_A)
print(la.det(A))

0.0365593376938
0.03655933769377926


In [101]:
# Problem 3

def solve_QR(A, b):
    m, n = A.shape
    nn = len(b)
    b = b.reshape(n, 1)
    if la.det(A) != 0 and n == m == nn:
        Q, R = mod_GS(A)
        y = Q.T @ b
        x = la.solve(R, y)
    return x

In [102]:
b = np.random.random(4)

In [103]:
x = solve_QR(A, b)

In [104]:
print(A@x, "Ax")
print(b.reshape(4, 1), "b")

[[ 0.97796503]
 [ 0.37076122]
 [ 0.06865832]
 [ 0.87018631]] Ax
[[ 0.97796503]
 [ 0.37076122]
 [ 0.06865832]
 [ 0.87018631]] b


In [127]:
# Problem 4

def HH(A):
    m, n = A.shape
    R = A.copy()
    Q = np.identity(m)
    sign = lambda x: 1 if x >= 0 else -1
    for k in range(n):
        u = R[k:,k]
        u[0] = u[0] + sign(u[0])*la.norm(u)
        u = u / la.norm(u)
        R[k:,k:] = R[k:,k:] - 2*np.outer(u, u.T@R[k:,k:])
        Q[k:,:] = Q[k:,:] - 2*np.outer(u, u.T@Q[k:,:])
    return Q.T, R